### ISSUE TITLE
Create a gif to demonstrate the available features of the bot

### ISSUE THREAD

**Issue by Link-** [mena-devs/bosta#25]
Add the gif to README

**Comment by aymanfarhat** [comment]
I think a gif would have to be too brief or it would be really big. Given that there is a lot of features, I think a youtube video would be easier to follow through. What do you think ?

**Comment by Link-** [comment]
This was meant more of a self note rather than a full explanation, sorry about that :D I was intending 1 brief gif per feature/plugin demonstrating it quickly not a big one for all of them combined

**Comment by aymanfarhat** [comment]
Ahh alright sounds great. How about making a dedicated file in the root directory such as "Demo.md" in it to have seperate subsections each describing the feature and under it a gif with usage.

**Comment by Link-** [comment]
Great idea, wanna handle that?

**Comment by aymanfarhat** [comment]
Sure :)

**Comment by Link-** [comment]
Stale
