### ISSUE TITLE
Add a "request more info" for invite admin alerts

### ISSUE THREAD

**Issue by aymanfarhat** [mena-devs/bosta#28]
Would be cool if we were able to automate the process related to requesting more info about the invitee's profile from the inviting member through the invite alert message. 

This could be triggered by having an additional button that we could call "Request more info". Example: 

![mock](https://cloud.githubusercontent.com/assets/823713/24298557/0373432a-10af-11e7-9b6b-b771c71374d5.jpg)

Suggested workflow:

1. Admin sees the invite alert on the admin channel and decides to request more info, Request info button is clicked.

2. Inviting slack member gets sent a template message by Bosta prompting the member to provide more information about the invitee. In the message Bosta mentions which admin requested to know more info about the invitee and asks the member to reach out to that admin with the information.

If we could detect which admin clicked on the request info button, then sending and mentioning who to reach out to would be pretty straightforward. My only concern is in case multiple admins click on that button multiple times, it would result in many DMs to the user. Which means, we will need to do a limit or delay between each message per member to prevent spamming. (Probably could be tracked in an in memmory DB like redis easily)

**Comment by Link-** [comment]
After research, it turns out that the workflow will require substantial effort at this stage and a simple message from a moderator to the user can sort out the issue.

**Comment by aymanfarhat** [comment]
Yeah it makes sense, agree.
