### ISSUE TITLE
Prevent greeting command from executing if user is already in the recent_users list

### ISSUE THREAD

**Issue by Link-** [mena-devs/bosta#29]
The manual greeting command should only be allowed if the user being greeted isn't already in the list of recent_users to avoid sending duplicate greeting messages i.e. spam

**Comment by phr34ck** [comment]
@Link- do you still want to work on this? I can start digging into the code and see how things work.

**Comment by Link-** [comment]
@phr34ck Yes! This would be a great start. Everything you need is in `newuser.js` and `system.js` plugins.

**Comment by Link-** [comment]
Stale
