### ISSUE TITLE
Data collection / statistics module

### ISSUE THREAD

**Issue by Link-** [mena-devs/bosta#44]
An important feature for Bosta is to collect chat statistics that Slack isn't allowing us to access. This list of items to monitor can be expanded here, starting with:

1. Number of messages sent by a person
2. Most frequent word used by the group
3. Activity per time of day and per day of the week
4. etc.

**Comment by constantine-nikolaou** [comment]
Could it also collect popular links for instance? ie: the ones with the most thumbsup

**Comment by Link-** [comment]
@cnicolaou The data is already collected, it'll simply be a matter of crafting the macro as per the below

-- Discussion between Bassem and @omaraboumrad 

1. Database to be seeded with historical logs for #general and #programming only and continuously updated as of the seeding point
2. Data to be stored in a tabular format with proper indexing

This module will allow users to craft custom queries to extract necessary insights.

### Examples

```
# Command Structure
@bosta create macro "Question that is bound to the query" with `Query Statement here`

# Example
@bosta create macro "who said hello the most in the past 3 months" with `SELECT name, COUNT(name) as total FROM chat_logs WHERE message @@ to_tsquery('hello') ORDER BY total DESC`

# Output
TBD
```

### Architecture

```
Bosta [Proxy] (collect messages, store into DB, parse commands, execute queries) > PostgreSQL [Database]
```

**Comment by Link-** [comment]
Stale
