### ISSUE TITLE
Negative karma abuse countermeasures 

### ISSUE THREAD

**Issue by Link-** [mena-devs/bosta#48]
### Proposal

As expected negative karma has proven to be a feature that requires more delicate care beyond the basic implementation. As such, I'm proposing the implementation of the following abuse countermeasures:

1. Limiting the use of the `-[1-5] @username` command to a certain configurable number per hour
2. Preventing users with negative karma of using the karma commands at all as a penalty
3. Notifying a user he/she received negative karma via a private message (debatable)
4. Making the penalty karma for negative points an increasing range instead of a fixed value of `-2` such that `[-1, -2, -3, -4, -5]` maps to the requester loosing `[-2, -3, -4, -5, -6]`.

### Proposal Discussion Period

This proposal is to be discussed here for the duration of `1 week` from the posting date, so that we can roll out the feature the soonest possible. After that we will roll out the common denominator.

### Abuse scenarios

**Scenario 1:** A user not caring about his/her own karma dropping below 0 could destroy the karma of another user for whatever reason and in stealth mode by sending karma commands to Bosta in DMs or in a non active channel.

**Scenario 2:** A user abusing negative karma to resolve a personal vendetta or in the anger spurring in a particular moment / heated debate.

### Voting

Just so that we don't re-iterate the same ideas over and over again, please just upvote the ones you wish to see in production.

**Comment by H889761123** [comment]
I agree to the general proposal and ideas, I just have this comment:
- A user should have at least a certain karma points in order to be allowed to use the negative karma feature.. my logic behind that is, the more a user has karma the less he/she will be involved in an abusive behavior.

**Comment by Link-** [comment]
Stale
